# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b10e6d3b0315de20bc3a7cfaf093088bca293bf10b88b97f242d5e0c858bea39324f7d6ad5ec3c4dee257247e4ae4936de5919b27f4bc31e55159f7dcc89880

test:
  secret_key_base: 88b027d53a5e6f4cfc35ef5012289db1ad55f3592e6ad5b06ca3ba93a14c2b8540362221c2dcc82c33b9ef8d43fe5f3a46afb85cca063d3b01ae3fcaa3fcc3a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
